apiVersion: apps/v1
kind: Deployment
metadata:
  name: thuong-nodejs-deployment
  namespace: thuong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thuong-nodejs-deployment
  template:
    metadata:
      labels:
        app: thuong-nodejs-deployment
    spec:
      containers:
      - name: thuong-nodejs
        image: huyduong1589/my-nodejs
        ports:
        - containerPort: 1313
        resources:
         limits:
          cpu: 100m
          memory: 100Mi
         requests:
          cpu: 50m
          memory: 50Mi


---
apiVersion: v1
kind: Service
metadata:
  name: thuong-nodejs-service
  namespace: thuong
spec:
  ports:
  - port: 1313
    targetPort: 1313
    protocol: TCP
    name: http
    nodePort: 30880
  selector:
    app: thuong-nodejs-deployment
  type: NodePort

